### ISSUE TITLE
Task list not properly detected

### ISSUE THREAD

**Issue by ShobanChiddarth** [simov/markdown-viewer#152]
These are task list previews in Github
*Screenshot*
![image](https://user-images.githubusercontent.com/68191453/130453377-e2f2491a-322e-4e86-8dd6-5080f26bbc5e.png)

*Code*
- [x] [links](https://www.example.com), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

These are task list previews in markdown viewer for Chrome
(Same code)
*Screenshot of code*
![image](https://user-images.githubusercontent.com/68191453/130453598-3fa0031a-4927-4c31-90bf-bf30aaa7dbc5.png)
*Screenshot of preview*
![image](https://user-images.githubusercontent.com/68191453/130453647-f51e9249-e989-468a-a176-a4cf5e8ded7c.png)

NOTE: gfm is enabled

**Comment by simov** [comment]
Hi, what exactly isn't working?

**Comment by ShobanChiddarth** [comment]
Tasklist (todos)

When I try to put a list in GitHub, I can get the task list without the '•'
But when I do the same in Markdown viewer, I get it only with that '•'

Here is the code I used:
```
- [x] [links](https://www.example.com), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
```

**Comment by simov** [comment]
Got it, I think that's due to the way the underlying compiler parses and renders it. I don't know which implementation should be considered the standard one, but either way this is a question to ask over on the [Marked](https://github.com/markedjs/marked) or the [Remark](https://github.com/remarkjs/remark) repository.

**Comment by simov** [comment]
Seems to be working in Markdown Viewer v5.2 for all of the supported compilers: marked, remark and markdown-it.

**Comment by ShobanChiddarth** [comment]
`remark` is the only thing that works properly

**Comment by simov** [comment]
I'm pretty sure it worked with markdown-it as well, though note that you have to enable the `footnotes` option first.

**Comment by ShobanChiddarth** [comment]
https://imgur.com/a/Q4gxt2D

**Comment by simov** [comment]
Oh did I say `footnotes`, I meant `tasklists`. Have a look at the compiler options for markdown-it here https://github.com/simov/markdown-viewer#compiler-options

**Comment by ShobanChiddarth** [comment]
`markdown-it` and `remark` are working now. `marked` is the only thing not working.
